// <auto-generated />
namespace CoffeeMaker.Migrations.Recipe
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateRecipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateRecipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201805190837110_CreateRecipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
